server:
  port: 8080
spring:
  application:
    name: dlp-api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://dlp-AUTHUSER-SERVICE
          predicates:
            - Path=/dlp-authuser/**
        - id: course-service
          uri: lb://dlp-COURSE-SERVICE
          predicates:
            - Path=/dlp-course/**
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost