server:
  port: 8080
spring:
  application:
    name: dlp-api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://dlp-AUTHUSER-SERVICE
          predicates:
            - Path=/dlp-authuser/**
        - id: course-service
          uri: lb://dlp-COURSE-SERVICE
          predicates:
            - Path=/dlp-course/**
        - id: notification-service
          uri: lb://DLP-NOTIFICATION-SERVICE
          predicates:
            - Path=/dlp-notification/**
dlp:
  serviceRegistry:
    username: serviceregistry
    password: 'dlp123sr'
eureka:
  client:
    service-url:
      defaultZone: 'http://${dlp.serviceRegistry.username}:${dlp.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost