FROM maven:3.8.4-openjdk-11 AS builder
WORKDIR /app

COPY pom.xml . 
RUN mvn dependency:go-offline
RUN mvn clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r target/
COPY src ./src
RUN mvn clean package  -Dmaven.test.skip
FROM adoptopenjdk:11-jre-hotspot
WORKDIR /app
COPY --from=builder /app/target/config-server-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8888
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ " curl -f http://configserver:dlp123cs@localhost:8888/actuator/health || exit 1" ]
CMD ["java", "-jar", "app.jar"]