FROM maven:3.8.4-openjdk-11 AS builder
WORKDIR /app
COPY pom.xml . 
RUN mvn dependency:go-offline
RUN mvn package

FROM adoptopenjdk:11-jre-hotspot
WORKDIR /app
COPY --from=builder /app/target/config-server-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8888

CMD ["java", "-jar", "app.jar"]
