# Dockerfile for api-gateway

FROM maven:3.8.4-openjdk-11 AS builder

WORKDIR /app

# Copy only the POM file to leverage Docker layer caching
COPY pom.xml .

# Download dependencies
RUN mvn dependency:go-offline

# Copy the source code and build the application
COPY src/ src/
RUN mvn package

# Create a lightweight image with only the JAR file
FROM adoptopenjdk:11-jre-hotspot

WORKDIR /app

COPY --from=builder /app/target/service-registry-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080


CMD ["java", "-jar", "app.jar"]
