server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authuser-ead
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
