spring:
  application:
    name: dlp-course-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: dlp-config-server
      username: configserver
      password: dlp123cs