server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ead-course
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      id.new_generator_mappings: true
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
