server:
  port: 8082
  servlet:
    context-path: '/dlp-course/'

spring:
  application:
    name: dlp-course-service
  datasource:
    url: jdbc:mysql://localhost:3306/dlp-course-sync
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      id.new_generator_mappings: true
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    com.dlp: TRACE
    root: INFO
    prg.springframework.web: DEBUG
dlp:
  api:
    url:
      authuser: 'http://dlp-authuser-service/dlp-authuser'
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
