server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/isabelanog/dlp-config-server-repo
          default-label: main
dlp:
  configServer:
    username: configserver
    password: dlp123cs
  serviceRegistry:
    username: serviceregistry
    password: 'dlp123sr'
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${dlp.serviceRegistry.username}:${dlp.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

