server:
  port: 8888
spring:
  application:
    name: dlp-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/isabelanog/dlp-config-server-repo
          default-label: main

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

